
apiVersion: v1
kind: Namespace
metadata:
  name: squirrel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: squirrel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: squirrel
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx
  namespace: squirrel
spec:
  host: nginx.apps.example.com
  to:
    kind: Service
    name: nginx
    weight: 100
  port:
    targetPort: 80
