## This document contains instructions for a new Kubernetes YAML that needs to be created,
## and the resultant YAML.
##
## The structure of the document is as follows:
## 1. Description of the desired YAML
## 2. The new YAML, terminated by an 'EOF'

## 1. Instructions for the new Kubernetes YAML:
create a Deployment which pulls a Jupyter Notebook image and requests 1 GPU resource

## 2. The new YAML:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - name: jupyter-notebook
        image: gcr.io/[PROJECT_ID]:latest
        env:
        - name: NODE_ENV
         