## This document contains instructions for a new Kubernetes YAML that needs to be created,
## and the resultant YAML.
##
## The structure of the document is as follows:
## 1. Description of the desired YAML
## 2. The new YAML, terminated by an 'EOF'

## 1. Instructions for the new Kubernetes YAML:
create a deployment of nginx with a service and route also create me a new namespace named squirrel

## 2. The new YAML:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    rollout_strategy: DeploymentReplace
    strategy: Recreate
    deployment.kubernetes.io/use-receipt-tracking: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx