backend: bloom
bloom:
  url: https://api-inference.huggingface.co/models/bigscience/bloom
  #generateParams:
    #seed: 0
    #early_stopping: false
    #length_penalty: 0
    #max_new_tokens: 150
    #do_sample: false
    #top_p: 0.9
